# Generated by Django 4.2.7 on 2025-10-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название проекта', max_length=200)),
                ('slug', models.SlugField(help_text='URL-адрес проекта', unique=True)),
                ('description', models.TextField(blank=True, help_text='Описание проекта')),
                ('technologies', models.CharField(help_text='Используемые технологии', max_length=255)),
                ('project_url', models.URLField(blank=True, help_text='Ссылка на проект')),
                ('github_url', models.URLField(blank=True, help_text='Ссылка на GitHub')),
                ('image', models.ImageField(blank=True, help_text='Главное изображение проекта', null=True, upload_to='portfolio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект портфолио',
                'verbose_name_plural': 'Проекты портфолио',
                'ordering': ['-created_at'],
            },
        ),
    ]
