# Generated by Django 4.2.7 on 2025-10-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioproject',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='budget',
            field=models.CharField(blank=True, help_text='Бюджет', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='category',
            field=models.CharField(blank=True, help_text='Категория проекта', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='client',
            field=models.CharField(blank=True, help_text='Клиент', max_length=200),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Обложка проекта для списка', null=True, upload_to='portfolio/covers/'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='duration',
            field=models.CharField(blank=True, help_text='Срок выполнения', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='gallery_image_1',
            field=models.ImageField(blank=True, help_text='Изображение галереи 1', null=True, upload_to='portfolio/gallery/'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='gallery_image_2',
            field=models.ImageField(blank=True, help_text='Изображение галереи 2', null=True, upload_to='portfolio/gallery/'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='gallery_image_3',
            field=models.ImageField(blank=True, help_text='Изображение галереи 3', null=True, upload_to='portfolio/gallery/'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='gallery_image_4',
            field=models.ImageField(blank=True, help_text='Изображение галереи 4', null=True, upload_to='portfolio/gallery/'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='team_size',
            field=models.CharField(blank=True, help_text='Размер команды', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='technologies',
            field=models.CharField(help_text='Используемые технологии (через запятую)', max_length=255),
        ),
    ]
